version: '3'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  service-a:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVICE_B_URL=http://service-b:8081
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
      - service-b

  service-b:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - WEATHER_API_KEY=50f58753404e4df0b97180249252008
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
